### PR TITLE
Give priority to focused field when looking for inputs

### PR DESCRIPTION
**Pull request by michele**
I started working on the focused fields PR as per issue #11.

It's probably still a bit rough, but it seems to work: it looks for a focused field, checks whether it's a password or login input and then goes on from there.

### CODE REVIEW

**Comment by michele** [comment]
I've added the iframe origin check here, too, it's on my master.

**Comment by martinhoefling** [comment]
thx @michele, I polished some parts a bit but your code makes a great addition. Two things: can you test the new version as well, before I make a new release? Second: I think the code deserves some tests. Can I ping you once this is set up? Maybe you can write / check the ones for this code.

**Comment by michele** [comment]
@martinhoefling I've been testing it this morning and it looks good to me. Let me know about the tests, I'll help if I can.

**Comment by martinhoefling** [comment]
@michele , I've merged some basic tests. Let me know if you would like to work on some tests for iframes and focus.

**Pull request merged**
